# Generated by Django 5.0.1 on 2024-01-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_welcome_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcome',
            old_name='types',
            new_name='type',
        ),
    ]
